# Generated by Django 4.1.5 on 2023-01-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
